### PR TITLE
Fixed: TKinter mousewheel scroll event won't work in Linux

### PR DESCRIPTION
**Pull request by aquawaves**

### CODE REVIEW

**Comment by kalabina** [comment]
Hi. It is possible to do an advanced video on how to use it (reference delta, scale, border, occluder and mouth). Example: On every mark I do during the video can I adjust with reference delta and border? Those reference delta and border they change auto based on the mark I put? Thank you in advance and Merry Christmas.
Untitled

**Comment by aquawaves** [comment]
> Hi. It is possible to do an advanced video on how to use it (reference delta, scale, border, occluder and mouth). Example: On every mark I do during the video can I adjust with reference delta and border? Those reference delta and border they change auto based on the mark I put? Thank you in advance and Merry Christmas. Untitled

Hello, yes, they do change from marker to marker. It's a whole point of using markers - setting up certain configuration at the specified point of video.

**Comment by aquawaves** [comment]
@Hillobar hi, is there any problem with pull request? If so, please comment on the lines that require fixing, will do.

**Comment by Chris-R-R** [comment]
I guess this isn't the correct place to put feature requests but I couldn't find anywhere else.

I would like to add the possibility to turn face enhancement with GFPGAN on or off depending on the orientation/pose, as the enhancement tends to add strange artefacts when the face is not looking directly at the camera.
For example, to turn off the enhancement if the pitch/roll/yaw of the face is 30 degrees or more away from the camera.

I tried to look up how to do this, OpenCV has a function called SolvePNP that might be useful but it seems to require 3d coordinates of the features in order to work. Perhaps there is something better available in the libraries Rope is already using?

Also, I notice that Rope sometimes swaps a face in a flickering manner, as if the face is detected in one frame and not the next. Perhaps it would be possible to look across multiple frames to improve this, to accept a lower threshold if a face was detected almost in the same position in the previous frame?

**Comment by aquawaves** [comment]
> I guess this isn't the correct place to put feature requests but I couldn't find anywhere else.
> 
> I would like to add the possibility to turn face enhancement with GFPGAN on or off depending on the orientation/pose, as the enhancement tends to add strange artefacts when the face is not looking directly at the camera. For example, to turn off the enhancement if the pitch/roll/yaw of the face is 30 degrees or more away from the camera.
> 
> I tried to look up how to do this, OpenCV has a function called SolvePNP that might be useful but it seems to require 3d coordinates of the features in order to work. Perhaps there is something better available in the libraries Rope is already using?
> 
> Also, I notice that Rope sometimes swaps a face in a flickering manner, as if the face is detected in one frame and not the next. Perhaps it would be possible to look across multiple frames to improve this, to accept a lower threshold if a face was detected almost in the same position in the previous frame?

You can request features in Discord server, you are absolutely right this isn't the right place for communication about requests as well as technical support.

**Comment by kalabina** [comment]
Also please I get this error:
E:\Rope-main\venv\lib\site-packages\torchvision\transforms\functional.py:1603: UserWarning: The default value of the antialias parameter of all the resizing transforms (Resize(), RandomResizedCrop(), etc.) will change from None to True in v0.17, in order to be consistent across the PIL and Tensor backends. To suppress this warning, directly pass antialias=True (recommended, future default), antialias=None (current default, which means False for Tensors and True for PIL), or antialias=False (only works on Tensors - PIL will still use antialiasing). This also applies if you are using the inference transforms from the models weights: update the call to weights.transforms(antialias=True).
Everything I write in CLIP doesn't do anything. I can change it myself but I don't know where. The rest is fine, I can swap faces but CLIP doesn't work. Thank you for who is willing to help me.

**Comment by aquawaves** [comment]
> Also please I get this error: E:\Rope-main\venv\lib\site-packages\torchvision\transforms\functional.py:1603: UserWarning: The default value of the antialias parameter of all the resizing transforms (Resize(), RandomResizedCrop(), etc.) will change from None to True in v0.17, in order to be consistent across the PIL and Tensor backends. To suppress this warning, directly pass antialias=True (recommended, future default), antialias=None (current default, which means False for Tensors and True for PIL), or antialias=False (only works on Tensors - PIL will still use antialiasing). This also applies if you are using the inference transforms from the models weights: update the call to weights.transforms(antialias=True). Everything I write in CLIP doesn't do anything. I can change it myself but I don't know where. The rest is fine, I can swap faces but CLIP doesn't work. Thank you for who is willing to help me.

Please consider bug report into Discord.
This error doesn't mean anything, just a warning for developers. To make CLIP work, type in your text, then press "Enter" so it will activate the prompt. Just typing it in and pressing on "CLIP" won't make it run.

**Comment by kalabina** [comment]
Thank you [aquawave](https://github.com/aquawaves). Also, I just found out a very easy way but I will be so happy with how to implement the Ruby, is called Pinokio, Like example: You can install Facefusion just with one click, he does everything automatically (tensorflow,cuda,bla bla bla).

**Comment by kalabina** [comment]
Hi. How do I use GPEN256? I downloaded it and put it inside the models folder but from the interface, I have only GFPGAN and CF

**Pull request closed without merging**
